version: '3.8'

services:
  hamkaroo_web:
    build: .
    container_name: hamkaroo_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - hamkaroo_db
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  hamkaroo_db:
    image: postgres:13
    container_name: hamkaroo_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DATABASE=hamkaroo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=poopoo
    ports:
      - "5432:5432"

  hamkaroo_adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: hamkaroo_db
    depends_on:
      - hamkaroo_db

volumes:
  postgres_data: